name: Terraform CI
run-name: ${{ github.actor }} is running Terraform CI.

on:
  # Add the workflow_dispatch event if you want to be able to manually run this workflow from the UI.
  # workflow_dispatch:
  # Add the push event, so that the workflow runs automatically every time a commit is pushed to a branch called main.
  # push:
  #  branches:
  #    - main
  # Add the pull_request event, so that the workflow runs automatically every time a pull request is created or updated.
  # pull_request:
  #  branches: [ "main" ]
  pull_request:
    branches:
      - main
jobs:
  Terraform-CI:
    name: Terraform-CI
    runs-on: ubuntu-latest

    steps:
    # Can we remove the name attribute and use - uses: actions/checkout@v3???
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
